### ISSUE TITLE
Get error "call cds to query app information failed" for publishing with release phase

### ISSUE THREAD

**Issue by cosic** [cianru/huawei-publish-gradle-plugin#10]
When trying to publish a build with release phase at `v1.2.0-snapshot` I get error:

>Execution failed for task ':app:publishHuaweiAppGalleryRelease'.
> Update App File Info is failed. Response: UpdateAppFileInfoResponse(ret=Ret(code=204144644, msg=[AppGalleryConnectPublishService]call cds to query app information failed))

**Comment by cosic** [comment]
I asked Huawei support. They confirmed the server issue. To work around this problem you should once set the release phase for uploader build from Developer Console. After that plugin should publish next builds without this error. 

![image](https://user-images.githubusercontent.com/2806586/97914705-5df06180-1d61-11eb-8cdf-d0a78c8503be.png)
Sorry for RU screenshot interface locale. Huawei doesn't allow me to change it on EN.

**Comment by cosic** [comment]
One more note. If already there is published version that waiting for review you'll get error:
>What went wrong:
>Execution failed for task ':app:publishHuaweiAppGalleryRelease'.
> Update App File Info is failed. Response: UpdateAppFileInfoResponse(ret=Ret(code=204144647, msg=[cds]update service failed, additional msg is [The new service has can't be edited service,which can't be updated!]))

**Comment by cosic** [comment]
Released at `v1.2.1`

**Comment by ilyamuromets** [comment]
I get the same error while publish draft version and the AGC have manual published version that waiting for review.

**Comment by cosic** [comment]
@ilyamuromets Which Gradle, AGP, Kotlin and Huawei Publishing Plugin versions are you using?

**Comment by ilyamuromets** [comment]
@cosic Gradle 7.4.1, AGP 7.0.4, Kotlin 1.6.10, Huawei Publishing Plugin 1.3.3
