### ISSUE TITLE
UPLOAD_ONLY mode don't work if it's a new apk for the same draft

### ISSUE THREAD

**Issue by zhelanov** [cianru/huawei-publish-gradle-plugin#17]
For some reason when I upload apk with UPLOAD_ONLY mode twice for the same draft it's not saving apk in AppGallery for a second (and further) upload.
For example, I may create app-1.0.apk and upload it. Then I'll see it on AppGallery Console web interface. Then I create app-1.1.apk and upload it too but it'll be not presented in AppGallery Console despite of log
```

Huawei AppGallery Publishing API: Upload build file '/path/to/app-1.0.apk'
Huawei AppGallery Publishing API: Upload build file without draft and submit on users - Successfully Done!
```

**Comment by ipBill** [comment]
It's not working. But  deployType = "draft". It's work for me.

**Comment by zhelanov** [comment]
Actually, UPLOAD_ONLY works but only once. `deployType = "DRAFT"` have it's own problem mentioned in issue #12

**Comment by zhelanov** [comment]
Well, now I can confirm that UPLOAD_ONLY really doesn't work at all from some moment :)

**Comment by zhelanov** [comment]
Well, I don't know how I've tested it before (because UPLOAD_ONLY worked) but now it really doesn't work. 

I've contacted Huawei support and asked them about apk uploading via API and they told me that it's **necessary** to do stage `Update App File Info`. So I'm sorry to force you to waste your time to implement this mode :(
