### ISSUE TITLE
The number of apk package is too many

### ISSUE THREAD

**Issue by kuFEAR** [cianru/huawei-publish-gradle-plugin#20]
Hi, I faced with error from AppGallery a few day ago, do you have idea what about it and how to fix this?
> Update App File Info is failed. Response: UpdateAppFileInfoResponse(ret=Ret(code=204144662, msg=[cds]add apk failed, additional msg is [90200503 The number of apk package is too many]))

**Comment by cosic** [comment]
@kuFEAR Hi! Have you tried to ask Huawei Support about this error?

**Comment by kuFEAR** [comment]
no, i don't. ok I'll try and back with feedback

**Comment by cosic** [comment]
@kuFEAR Hi! Do you have any news?

**Comment by kuFEAR** [comment]
Hi, when I’ve change deployType 'draft' to 
upload-only' then error is gone, also I’ve remove a draft from huawei console, as I understand it has limitation on active drafts at the same time and will throw an error
