### ISSUE TITLE
App publication requires additional manual step to be available for users

### ISSUE THREAD

**Issue by dbarwacz** [cianru/huawei-publish-gradle-plugin#21]
Hello! 
I integrated this plugin quite effortlessly, many thanks! 
After testing I realised though that the publications are not automatically submitted for review. I would like it to submit the build in a way, that it's available to the users with no further human action. The reality is that it requires me to manually click 'submit' in the console. I additionally receive an email from huawei that `Promotion has been enabled for your app #appname# (#appid#).` Is this expected? I publish with default config (ie default deployType, regular apk). Is this how this should behave?

**Comment by bcarrera** [comment]
1.2.3-SNAPSHOT should fix your problem -> https://github.com/cianru/huawei-publish-gradle-plugin/pull/19#issuecomment-769884670

**Comment by dbarwacz** [comment]
Is it likely that it will lend as a release? I would like to avoid having a crucial release step depending on a snapshot release that could break any minute with new version. Can I help with that somehow?

**Comment by cosic** [comment]
@dbarwacz Hi, The `1.2.3-SNAPSHOT` is stable version and I won't to change it. Later I'm going to release it as v1.2.4.

**Comment by cosic** [comment]
Release at v1.2.4
