### ISSUE TITLE
Looking for buildFile wildcard example

### ISSUE THREAD

**Issue by henorek** [cianru/huawei-publish-gradle-plugin#22]
Hello there,
Could you please give me an example of the use of the buildFile parameter?

I need to match any apk file contained under the path, but the following code unfortunately does not work

`buildFile = "app/build/outputs/apk/release/*.apk"`

**Comment by cosic** [comment]
@henorek Hi! Try to use something like that https://github.com/cianru/huawei-publish-gradle-plugin/issues/16#issuecomment-749669382

**Comment by cosic** [comment]
Ok, I duplicate the answer and close the ticket. Try to execute the gradle task and give it apk file path by unix tools like that
```
./gradlew publishHuaweiAppGalleryRelease \                                                                                                                               ✔     
    --buildFile=$(ls ./app/build/outputs/apk/release/*.apk| head -1) \
    --buildFormat=apk
```
