### ISSUE TITLE
Failure on code 204144727 "The package is being compiled, please try again in 3-5 minutes"

### ISSUE THREAD

**Issue by vlad-roid** [cianru/huawei-publish-gradle-plugin#24]
Hi, Huawei AppGallery recently had some changes, not sure when, but they caused the plugin to fail at the final step:
```
Huawei AppGallery Publishing API: Submit Review

> Task :publishHuaweiAppGallery...Release FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':publishHuaweiAppGallery...Release'.
> SubmitResponse(ret=Ret(code=204144727, msg=[AppGalleryConnectPublishService]The package is being compiled, please try again in 3-5 minutes))
```
The solution for now is after these "3-5 minutes" to go to their dashboard and publish the update manually, but very annoying. Please fix, probably you can just add a delay after this error comes and reattempt every minute.

**Comment by cosic** [comment]
@vlad-roid Hi? Which Gradle version, Android Gradle Plugin and Plugin Params are you using?

**Comment by cosic** [comment]
Need more info
