### ISSUE TITLE
support AGP 7.0.0 

### ISSUE THREAD

**Issue by BugsBunnyBR** [cianru/huawei-publish-gradle-plugin#25]
Does this plugin support AGP 7.0.0 ?

**Comment by cosic** [comment]
@BugsBunnyBR Not yet, but soon

**Comment by cosic** [comment]
@BugsBunnyBR Could you try `1.3.0-SNAPSHOT` version?

**Comment by gotev** [comment]
It works for me 😉 https://github.com/cianru/huawei-publish-gradle-plugin/issues/23#issuecomment-902549936

**Comment by cosic** [comment]
v1.3.0 released. Thx!

**Comment by BugsBunnyBR** [comment]
Thanks
