### ISSUE TITLE
Feature request: Publish as open testing 

### ISSUE THREAD

**Issue by AndrazP** [cianru/huawei-publish-gradle-plugin#34]
I would love to see an option to publish a release as **open testing**.

Right now my solution is to deploy as draft and then manually fill out open testing options:
<img width="1123" alt="Screenshot 2021-12-08 at 15 15 24" src="https://user-images.githubusercontent.com/1963904/145223890-39831744-92f9-42e2-b2e7-9ab9f0e1e60c.png">

**Comment by AndrazP** [comment]
@cosic Does the API even support setting these fields?
I'm happy to help develop this feature if it's feasble.

**Comment by cosic** [comment]
@AndrazP Hi. I looked for API methods but have not found. So I asked huawei support and they unfortunately answer
> Huawei customer support
> 2021-12-13 14:14:54 GMT+03:00
> Dear developer,
> Thank you for your question! Unfortunately, There is no method for Open Testing in Publish API, and we don't have plans about it for now.
>
>Have a nice day.
>HUAWEI DTSE

**Comment by AndrazP** [comment]
Thanks for asking them.
