### ISSUE TITLE
publishHuaweiAppGallery* task not created for all build types

### ISSUE THREAD

**Issue by AndrazP** [cianru/huawei-publish-gradle-plugin#36]
README says:
> Gradle generate publishHuaweiAppGallery* task for each buildType configuration those have debuggable=false option.

I can't get it to work for other build types than `debug ` and `release`.
I also tried in this project example `sample-groovy`
https://github.com/AndrazP/huawei-publish-gradle-plugin/commit/5b0c4d4100a929b1545f9fa65d2933a720c81785
I would expect it to generate task `publishHuaweiAppGalleryInternalTest`.

**Comment by cosic** [comment]
@AndrazP  Hi
> Gradle generate publishHuaweiAppGallery* task for each buildType configuration those have debuggable=false option.

Yeah. That's right. If you execute next command
```
./gradlew tasks
```
 into current repository then you can find next tasks in output
```
// for sample-groovy;
publishHuaweiAppGalleryDemoRelease - Upload and publish application build file to Huawei AppGallery Store for demoRelease buildType
publishHuaweiAppGalleryFullRelease - Upload and publish application build file to Huawei AppGallery Store for fullRelease buildType

// for sample-kotlin;
publishHuaweiAppGalleryRelease - Upload and publish application build file to Huawei AppGallery Store for release buildType
```
I check it. The plugin in `master` branch work as well. 

Could you show me `build.gradle` file in you application module for more information?

**Comment by AndrazP** [comment]
Did you check my example 
https://github.com/AndrazP/huawei-publish-gradle-plugin/commit/5b0c4d4100a929b1545f9fa65d2933a720c81785
where I added build type `internalTest`?
`publishHuaweiAppGalleryInternalTest` is not generated.

**Comment by cosic** [comment]
@AndrazP you are right. I've found issue and remove debaggable restriction in `1.3.2-SNAPSHOT` version. Please check it. Plugin will create task for all project buildTypes. If the issue fixed I'll publish it in next release.

**Comment by AndrazP** [comment]
`internalTest` build type in my example has `debuggable false` but task was not generated with version 1.3.1.
1.3.2-SNAPSHOT successfully generates  `publishHuaweiAppGallery*` tasks for all build types. With `debuggable false` and `debuggable true`
Thanks for the quick response!

**Comment by cosic** [comment]
Release at v1.3.3
