### ISSUE TITLE
Please add an option to update Whats New for the build

### ISSUE THREAD

**Issue by biodranik** [cianru/huawei-publish-gradle-plugin#37]
It would be very convenient to upload at least a whats new text of up to 1000 characters for every build.

**Comment by cosic** [comment]
This linlk for me https://developer.huawei.com/consumer/en/doc/development/AppGallery-connect-References/agcapi-language-info-update-0000001158245057

**Comment by cosic** [comment]
@biodranik Hi. Sorry for late reaction. Could you try a new `releaseNotes` Plugin parameter to update Release Notes? See more detailed at `README.md`

**Comment by biodranik** [comment]
@cosic thanks! In the [README](https://github.com/cianru/huawei-publish-gradle-plugin#plugin-params) you mention that the limit is 500 characters. Did you test it with 1000 chars? Because Huawei allows using of up to 1000 characters from their admin console with the manual upload.

**Comment by cosic** [comment]
@biodranik No, I didn't test with 1000 chars coz [documentation](https://developer.huawei.com/consumer/en/doc/development/AppGallery-connect-References/agcapi-language-info-update-0000001158245057) says that 500 chars is maximum.

**Comment by biodranik** [comment]
Wow, looks like they cut it for some reason, or maybe made a mistake. Do you have any contacts to report this inconsistency? It is possible to use 1000 chars manually in the console.

**Comment by cosic** [comment]
@biodranik @biodranik Google Play also [restricts Release Notes with 500 chars](https://support.google.com/googleplay/android-developer/answer/9859348?hl=en#zippy=%2Cwhats-new-in-this-release). I guess it's an ussual case to use the same release notes for Google Play and Huawei AppGallery. 

But the way latter I'll try to upload Release Notes more than 500 chars for my interesting. I want to create separately Gradle Task to update Release Notes without uploading a new build.

**Comment by biodranik** [comment]
@cosic 
1. Did you try to upload more than 500 characters?
2. Also, would it be possible to support [this file](https://github.com/organicmaps/organicmaps/tree/master/android/src/fdroid/play) structure to upload whatsnew, or even better, to update all app's metadata? It's documented here: https://f-droid.org/docs/All_About_Descriptions_Graphics_and_Screenshots/#triple-t-structure

It will save a lot of manual time for app updates.

**Comment by cosic** [comment]
@biodranik Hi,
> 1. Did you try to upload more than 500 characters?

Yes, I did and got next error from Huawei Publushing API:

```Update Release Notes for 'ru-RU' is failed. Response: UpdateReleaseNotesResponse(ret=Ret(code=203489281, msg=[AppGalleryConnectPublishService]updateAppLanguageInfo.arg2.newFeatures: size must be between 0 and 500))```

----
> 2. Also, would it be possible to support [this file](https://github.com/organicmaps/organicmaps/tree/master/android/src/fdroid/play) structure to upload whatsnew, or even better, to update all app's metadata? It's documented here: https://f-droid.org/docs/All_About_Descriptions_Graphics_and_Screenshots/#triple-t-structure It will save a lot of manual time for app updates.

I think it's a bad idea to use the same file structure from other project due to my plugin will be strongly depended on thirtparty project however I even doesn't use it directly. If they sometime will change the file structure then it leads to a bug into my plugin.

Instead of it I did create a flexible settings for release notes. So you can reuse the release notes files of Triple file. For example:

```
huaweiPublish {
    instances {
        release {
            releaseNotes = [
                new ru.cian.huawei.publish.ReleaseNote(
                    "en-En",
                    "$projectDir/src/main/play/release-notes/en-En/default.txt"
                ),
                new ru.cian.huawei.publish.ReleaseNote(
                    "ru-RU",
                    "$projectDir/src/main/play/release-notes/ru-RU/default.txt"
                ),
                new ru.cian.huawei.publish.ReleaseNote(
                    "de-DE",
                    "$projectDir/src/main/play/release-notes/de-DE/default.txt"
                ),
                new ru.cian.huawei.publish.ReleaseNote(
                    "tr-TR",
                    "$projectDir/src/main/play/release-notes/tr-TR/default.txt"
                ),
                new ru.cian.huawei.publish.ReleaseNote(
                    "pt-BR",
                    "$projectDir/src/main/play/release-notes/pt-BR/default.txt"
                ),
            ]
        }
    }
}
```

**Comment by biodranik** [comment]
Thanks! @rtsisyk can you please support it?
