### ISSUE TITLE
Publishing bug: The package is being compiled, please try again

### ISSUE THREAD

**Issue by iliaskomp** [cianru/huawei-publish-gradle-plugin#38]
It seems that [this issue](https://github.com/cianru/huawei-publish-gradle-plugin/issues/32) has reappeared with the latest huawei publish plugin version (1.3.1):

```
> Task :app:publishHuaweiAppGalleryRelease
Huawei AppGallery Publishing API: Generate Config
Huawei AppGallery Publishing API: Found build file: `release.apk`
Huawei AppGallery Publishing API: Get Access Token
Huawei AppGallery Publishing API: Get App ID
Huawei AppGallery Publishing API: Get Upload Url
Huawei AppGallery Publishing API: Upload build file 'app/build/outputs/apk/release/release.apk'
Huawei AppGallery Publishing API: Update App File Info
Huawei AppGallery Publishing API: Submit Review
> Task :app:publishHuaweiAppGalleryRelease FAILED
FAILURE: Build failed with an exception.
* What went wrong:
Execution failed for task ':app:publishHuaweiAppGalleryRelease'.
> SubmitResponse(ret=Ret(code=204144727, msg=[AppGalleryConnectPublishService]The package is being compiled, please try again in 3-5 minutes))
```

**Versions**
Huawei publish gradle plugin: 1.3.1
Gradle 7.2.0
AGP: 7.1.2

**Comment by cosic** [comment]
@iliaskomp Hi, I've reproduced. I guess than Huawei changed the behavior of current api url for `apk` build and taken it as for `aab` with waiting of review. I going to deal with this soon.

**Comment by cosic** [comment]
@iliaskomp As I've supposed. Please check you case on `1.3.3-SNAPSHOT` version.

**Comment by iliaskomp** [comment]
Thank you for your quick response.
Is the artifact published? I am getting the error: `Could not find ru.cian:huawei-publish-gradle-plugin:1.3.3-SNAPSHOT`

**Comment by cosic** [comment]
@iliaskomp Yes, the artifact published. You can check it [here](https://oss.sonatype.org/#nexus-search;quick~ru.cian). Did you add Sonatype SNAPSHOT repository to dependencies from README tutorial? 
```
repositories {
        maven { url 'https://oss.sonatype.org/content/repositories/snapshots' }
}
```

**Comment by iliaskomp** [comment]
Oh thanks, using this repository for the snapshop resolves the artifact

**Comment by cosic** [comment]
Release at v1.3.3
