### ISSUE TITLE
Java 8 incompatibility

### ISSUE THREAD

**Issue by SherzodAgzamov** [cianru/huawei-publish-gradle-plugin#39]
is there any way to downgrade the java version or solve the compatibility problem? My project uses java 8 and there is no way to increase the version 

Gradle version: 7.4.2
AGP version: 7.0.4
Kotlin version: 1.5.20

* What went wrong:
A problem occurred configuring root project 'build'.
> Could not resolve all files for configuration ':classpath'.
   > Could not resolve ru.cian:huawei-publish-gradle-plugin:1.3.3.
     Required by:
         project :
      > No matching variant of ru.cian:huawei-publish-gradle-plugin:1.3.3 was found. The consumer was configured to find a runtime of a library compatible with Java 8, packaged as a jar, and its dependencies declared externally, as well as attribute 'org.gradle.plugin.api-version' with value '7.4.2' but:
          - Variant 'apiElements' capability ru.cian:huawei-publish-gradle-plugin:1.3.3 declares a library, packaged as a jar, and its dependencies declared externally:
              - Incompatible because this component declares an API of a component compatible with Java 11 and the consumer needed a runtime of a component compatible with Java 8
              - Other compatible attribute:
                  - Doesn't say anything about org.gradle.plugin.api-version (required '7.4.2')
          - Variant 'runtimeElements' capability ru.cian:huawei-publish-gradle-plugin:1.3.3 declares a runtime of a library, packaged as a jar, and its dependencies declared externally:
              - Incompatible because this component declares a component compatible with Java 11 and the consumer needed a component compatible with Java 8
              - Other compatible attribute:
                  - Doesn't say anything about org.gradle.plugin.api-version (required '7.4.2')

**Comment by cosic** [comment]
@SherzodAgzamov Hi! Unfortunately since v7.0+ of AGP is required to use JAVA11 https://developer.android.com/studio/releases/gradle-plugin#jdk-11

**Comment by SherzodAgzamov** [comment]
@cosic In version 1.2.5, the application is uploaded to the app gallery but not submitted, and this fix is in version 1.3.3. I thought to upgrade version, but no luck. By the way, thanks for the reply

**Comment by cosic** [comment]
@SherzodAgzamov Yes `v1.2.5` is last version that support AGP4.* and less and hence JAVA8. I saved `snapshot-1.2.5` branch to fix bugs if they appears. Unforcutately there isn't way to support APG4 and AGP7 dependencies and restriction at the same time.

**Comment by SherzodAgzamov** [comment]
@cosic Is it possible to merge the fix #38 from `v1.3.3` to `snapshot-1.2.5`?

**Comment by cosic** [comment]
@SherzodAgzamov Yeap. Guess I can make cherry-pick and release v1.2.6

**Comment by SherzodAgzamov** [comment]
oh, that would be great!

**Comment by cosic** [comment]
@SherzodAgzamov Please check fix of #38 on `1.2.6-SNAPSHOT` version.

**Comment by SherzodAgzamov** [comment]
@cosic oh well, snapshot works great! thanks a lot!

**Comment by cosic** [comment]
Released at v1.2.6
