### ISSUE TITLE
huawei-publish-gradle-plugin:1.2.5 - problem with distribution tag: upload-only nothing uploads on AGC

### ISSUE THREAD

**Issue by Adza93** [cianru/huawei-publish-gradle-plugin#40]
Looks like the whole process passes without an issue however I cannot find ADB file on AGC manage packages page.

Build output: 
Final command: ./gradlew bundleRelease publishHuaweiAppGalleryRelease

Output:
```
> Task :publishHuaweiAppGalleryRelease
Huawei AppGallery Publishing API: Generate Config
Huawei AppGallery Publishing API: Found build file: `app-name.aab`
Huawei AppGallery Publishing API: Get Access Token
Huawei AppGallery Publishing API: Get App ID
Huawei AppGallery Publishing API: Get Upload Url
Huawei AppGallery Publishing API: Upload build file '{localFileLocation}/build/outputs/bundle/release/app-name.aab'
Huawei AppGallery Publishing API: Upload build file without draft and submit on users - Successfully Done!
```

Is this a plugin issue or maybe problems with AGC API? 
I am using plugin version 1,2.5 due to compatibility with gradle v6.8.3 is being used in the project.

Thanks for help :)

**Comment by alperenbabagil** [comment]
Same here

**Comment by cosic** [comment]
Hi! @Adza93 @alperenbabagil 
I don't have real project with Gradle 6.* and AGP 4.*. So you must help to figure out with it. Let's try next steps:
1.) Try to use a new `1.2.6` plugin version for old projects. If it doen't work as well than try next step.
2.) Try to `1.2.7-SNAPSHOT` version with option `--info` to get a little bit more info about each pulishing step. For example: 
```
./gradlew publishHuaweiAppGalleryRelease --info
```
Please hide security params in your result logs and send it to me.

P.S> When you'll use SNAPSHOT version don't forget to add `maven { url 'https://oss.sonatype.org/content/repositories/snapshots' }` snapshots repository.

**Comment by alperenbabagil** [comment]
We used draft option and it works perfectly

**Comment by cosic** [comment]
@alperenbabagil  Can you tell me more detailed? Have you tried v1.2.6? Or does the plugin work on v1.2.5 only with DRAFT option?

**Comment by cosic** [comment]
I need more info to reproduse issue. So I close this issue now. Please reopen one if it relevant for you or provide me more information.
