### ISSUE TITLE
Support phased release

### ISSUE THREAD

**Issue by frmz** [cianru/huawei-publish-gradle-plugin#5]
Would be nice to have an option to use phased release:
https://developer.huawei.com/consumer/en/doc/distribution/app/agc-phased_release

**Comment by cosic** [comment]
Release by phases API doesn't work as well. So I will finish this feature later.
![image](https://user-images.githubusercontent.com/2806586/96255260-46725400-0fbf-11eb-973d-5a6eebca2631.png)

**Comment by cosic** [comment]
The feature is available at `1.2.1-SNAPSHOT` plugin version but before please read the README.md file to know a known Huawei issues.

**Comment by cosic** [comment]
Released at `v1.2.1`
